services:
  gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - health_care
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount file cấu hình Nginx
    networks:
      - app-network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network
    volumes:
      - ./auth_service:/app

  health_care:
    build:
      context: ./HealthCareSystem
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ./HealthCareSystem:/app

networks:
  app-network:
    driver: bridge